apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: everundang

bases:
  - ../../base

patchesStrategicMerge:
  - replicas-patch.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:5173
      - FRONTEND_ORIGINS=http://localhost:5173,http://frontend:80

  - name: frontend-config
    behavior: merge
    literals:
      - VITE_API_URL=http://localhost:4000
