apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: everundang

bases:
  - ../../base

patchesStrategicMerge:
  - replicas-patch.yaml
  - resources-patch.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - NODE_ENV=production

secretGenerator:
  - name: backend-secret
    behavior: replace
    literals:
      - ADMIN_SECRET=${ADMIN_SECRET}
      - INVITE_OWNER_JWT_SECRET=${INVITE_OWNER_JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
