apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: everundang
  labels:
    app.kubernetes.io/name: everundang
    app.kubernetes.io/component: frontend
data:
  VITE_API_URL: "http://backend:4000"
