apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: everundang

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-secret.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-route.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-route.yaml

commonLabels:
  app.kubernetes.io/name: everundang
  app.kubernetes.io/managed-by: kustomize
